# Generated by Django 4.2.9 on 2025-12-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthprofile',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
