# Generated by Django 4.2.9 on 2025-10-03 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantPhenology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimalLongitude', models.DecimalField(blank=True, decimal_places=6, help_text='地理座標經度（十進位）', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('decimalLatitude', models.DecimalField(blank=True, decimal_places=6, help_text='地理座標緯度（十進位）', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('minimumElevationInMeters', models.IntegerField(blank=True, help_text='最低海拔(公尺)', null=True)),
                ('maximumElevationInMeters', models.IntegerField(blank=True, help_text='最高海拔(公尺)', null=True)),
                ('vernacularName', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonID', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('verbatimLocality', models.CharField(max_length=255)),
                ('scientificName', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('taxonRank', models.CharField(blank=True, max_length=64, null=True)),
                ('locality', models.CharField(max_length=255)),
                ('locationID', models.CharField(max_length=128)),
                ('eventDate', models.DateField()),
                ('eventID', models.CharField(db_index=True, max_length=255)),
                ('dataID', models.CharField(db_index=True, max_length=255)),
                ('organismID', models.CharField(blank=True, max_length=255, null=True)),
                ('samplingProtocol', models.CharField(blank=True, choices=[('woody', 'woody'), ('herb', 'herb')], max_length=16, null=True)),
                ('recordedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('canopyCoverPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('budCoverPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('newLeafCoverPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('matureLeafCoverPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('yellowLeafCoverPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deadLeafCoverPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('totalFlowerCount', models.PositiveIntegerField(blank=True, null=True)),
                ('budFlowerPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fullBloomPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('wiltedFlowerPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('totalFruitCount', models.PositiveIntegerField(blank=True, null=True)),
                ('youngFruitPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('greenFruitPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ripeFruitPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('wiltedFruitPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coverInPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('herbaceousPlantHeight', models.PositiveIntegerField(blank=True, help_text='草本高度(公分)', null=True)),
                ('individualCount', models.PositiveIntegerField(blank=True, null=True)),
                ('fruitCount', models.PositiveIntegerField(blank=True, null=True)),
                ('flowerCount', models.PositiveIntegerField(blank=True, null=True)),
                ('budCount', models.PositiveIntegerField(blank=True, null=True)),
                ('wiltedPercentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('animalGrazing', models.BooleanField(blank=True, null=True)),
                ('sampleSizeValue', models.FloatField(blank=True, null=True)),
                ('sampleSizeUnit', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PlantPhenology',
                'verbose_name_plural': 'PlantPhenology',
                'db_table': 'plant_phenology',
                'indexes': [models.Index(fields=['eventID'], name='plant_pheno_eventID_519abd_idx'), models.Index(fields=['dataID'], name='plant_pheno_dataID_0c62ec_idx'), models.Index(fields=['taxonID'], name='plant_pheno_taxonID_4a052e_idx'), models.Index(fields=['scientificName'], name='plant_pheno_scienti_0192a8_idx')],
            },
        ),
    ]
