# Generated by Django 4.2.9 on 2025-10-03 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantphenology',
            name='decimalLatitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='地理座標緯度（十進位）', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='plantphenology',
            name='decimalLongitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='地理座標經度（十進位）', max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
