# Generated by Django 4.2.9 on 2025-10-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_plantphenology_decimallatitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantPhenologyDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_name_zh_tw', models.CharField(max_length=255)),
                ('field_name_en', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=100)),
                ('show_at_frontend', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plant_phenology_data_field',
            },
        ),
    ]
