# Generated by Django 4.2.9 on 2025-10-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_plantphenologydatafield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantphenologydatafield',
            old_name='show_at_frontend',
            new_name='show_at_filter',
        ),
        migrations.AddField(
            model_name='plantphenologydatafield',
            name='show_at_table',
            field=models.BooleanField(default=True),
        ),
    ]
