# Generated by Django 4.2.9 on 2025-10-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_show_at_frontend_plantphenologydatafield_show_at_filter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_item', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=20)),
                ('location_id', models.CharField(max_length=10)),
                ('decimalLongitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('decimalLatitude', models.DecimalField(decimal_places=10, max_digits=12)),
            ],
        ),
    ]
