# Generated by Django 4.2.9 on 2025-10-31 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='decimalLatitude',
            new_name='decimal_latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='decimalLongitude',
            new_name='decimal_longitude',
        ),
    ]
