# Generated by Django 4.2.9 on 2025-10-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_decimallatitude_location_decimal_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camtrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observationType', models.CharField(choices=[('animal', 'animal'), ('human', 'human'), ('vehicle', 'vehicle'), ('blank', 'blank'), ('unknown', 'unknown'), ('unclassified', 'unclassified')], help_text='觀察的類型', max_length=32)),
                ('observationLevel', models.CharField(choices=[('event', 'event'), ('media', 'media')], help_text='觀察的分類級別', max_length=16)),
                ('observationComments', models.TextField(blank=True, help_text='有關觀察的評論或備註', null=True)),
                ('deploymentID', models.CharField(db_index=True, help_text='機器部署的唯一識別碼', max_length=128)),
                ('timestamp', models.DateTimeField(help_text='記錄媒體文件的日期和時間')),
                ('eventDate', models.DateField(db_index=True, help_text='事件發生的具體日期')),
                ('eventTime', models.TimeField(help_text='事件發生的具體時間')),
                ('locationRemarks', models.CharField(blank=True, help_text='關於地點的附註', max_length=255, null=True)),
                ('scientificName', models.CharField(db_index=True, help_text='觀察到的個體的學名', max_length=255)),
                ('scientificNameAuthorship', models.CharField(blank=True, help_text='學名的命名者', max_length=255, null=True)),
                ('scientificNameID', models.CharField(blank=True, db_index=True, help_text='TaiCOL 學名識別碼', max_length=128, null=True)),
                ('vernacularName', models.CharField(blank=True, help_text='生物的常用名稱', max_length=255, null=True)),
                ('taxonID', models.CharField(blank=True, db_index=True, help_text='TaiCOL 物種編號', max_length=128, null=True)),
                ('taxonRank', models.CharField(blank=True, help_text='物種鑑定的最小分類單元', max_length=64, null=True)),
                ('family', models.CharField(blank=True, help_text='科的科學名稱', max_length=128, null=True)),
                ('familyChinese', models.CharField(blank=True, help_text='科中文名', max_length=128, null=True)),
                ('fileName', models.CharField(blank=True, help_text='媒體文件的名稱', max_length=255, null=True)),
                ('filePath', models.CharField(blank=True, help_text='媒體文件的 URL 或相對路徑', max_length=1024, null=True)),
                ('filePublic', models.BooleanField(default=False, help_text='媒體文件是否可公開訪問')),
                ('fileMediatype', models.CharField(help_text='媒體文件的媒體類型', max_length=64)),
                ('mediaID', models.CharField(help_text='媒體的識別碼', max_length=255, unique=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('hermaphrodite', 'hermaphrodite'), ('ambiguous', 'ambiguous')], help_text='生物的性別', max_length=16, null=True)),
                ('lifeStage', models.CharField(blank=True, choices=[('adult', 'adult'), ('subadult', 'subadult'), ('juvenile', 'juvenile')], help_text='年齡或生命階段', max_length=16, null=True)),
                ('count', models.PositiveIntegerField(blank=True, help_text='數量', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camtrap',
                'verbose_name_plural': 'Camtrap',
                'db_table': 'camtrap',
                'indexes': [models.Index(fields=['deploymentID'], name='camtrap_deploym_696f32_idx'), models.Index(fields=['eventDate'], name='camtrap_eventDa_fde380_idx'), models.Index(fields=['scientificName'], name='camtrap_scienti_e95df5_idx'), models.Index(fields=['taxonID'], name='camtrap_taxonID_9bee6d_idx')],
            },
        ),
    ]
