# Generated by Django 4.2.9 on 2025-10-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_camtrap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camtrap',
            new_name='Cameratrap',
        ),
        migrations.AlterModelOptions(
            name='cameratrap',
            options={'verbose_name': 'Cameratrap', 'verbose_name_plural': 'Cameratrap'},
        ),
    ]
