# Generated by Django 4.2.9 on 2025-10-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_camtrap_cameratrap_alter_cameratrap_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cameratrap',
            name='camtrap_scienti_e95df5_idx',
        ),
        migrations.AlterField(
            model_name='cameratrap',
            name='scientificName',
            field=models.CharField(blank=True, help_text='觀察到的個體的學名', max_length=255, null=True),
        ),
    ]
