# Generated by Django 4.2.9 on 2025-11-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cameratrap_camtrap_scienti_e95df5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='decimal_latitude',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='location',
            name='decimal_longitude',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
