# Generated by Django 4.2.9 on 2025-11-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_location_decimal_latitude_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cameratrap',
            new_name='api_camtrap_deploym_22af27_idx',
            old_name='camtrap_deploym_696f32_idx',
        ),
        migrations.RenameIndex(
            model_name='cameratrap',
            new_name='api_camtrap_eventDa_30d7e8_idx',
            old_name='camtrap_eventDa_fde380_idx',
        ),
        migrations.RenameIndex(
            model_name='cameratrap',
            new_name='api_camtrap_taxonID_0c4a6d_idx',
            old_name='camtrap_taxonID_9bee6d_idx',
        ),
        migrations.RenameIndex(
            model_name='plantphenology',
            new_name='api_plant_p_eventID_f12eb0_idx',
            old_name='plant_pheno_eventID_519abd_idx',
        ),
        migrations.RenameIndex(
            model_name='plantphenology',
            new_name='api_plant_p_dataID_b0a4b2_idx',
            old_name='plant_pheno_dataID_0c62ec_idx',
        ),
        migrations.RenameIndex(
            model_name='plantphenology',
            new_name='api_plant_p_taxonID_977bd4_idx',
            old_name='plant_pheno_taxonID_4a052e_idx',
        ),
        migrations.RenameIndex(
            model_name='plantphenology',
            new_name='api_plant_p_scienti_35416b_idx',
            old_name='plant_pheno_scienti_0192a8_idx',
        ),
        migrations.AddField(
            model_name='cameratrap',
            name='locationID',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='cameratrap',
            table='api_camtrap',
        ),
        migrations.AlterModelTable(
            name='plantphenology',
            table='api_plant_phenology',
        ),
        migrations.AlterModelTable(
            name='plantphenologydatafield',
            table='api_plant_phenology_data_field',
        ),
    ]
