# Generated by Django 4.2.9 on 2025-11-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_camtrap_deploym_696f32_idx_api_camtrap_deploym_22af27_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameratrap',
            name='count',
        ),
        migrations.RemoveField(
            model_name='cameratrap',
            name='lifeStage',
        ),
        migrations.RemoveField(
            model_name='cameratrap',
            name='mediaID',
        ),
        migrations.AddField(
            model_name='cameratrap',
            name='observationID',
            field=models.CharField(db_index=True, default='', help_text='觀察物種的識別碼', max_length=256),
            preserve_default=False,
        ),
    ]
