# Generated by Django 4.2.9 on 2025-11-17 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_cameratrap_count_remove_cameratrap_lifestage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(help_text='每筆資料的辨識碼，以調查事件ID+流水號。', max_length=255)),
                ('eventID', models.CharField(help_text='每筆調查事件的辨識碼，以子計畫代碼+調查日期+地點+樣區編號為組成。', max_length=255)),
                ('classid', models.IntegerField(blank=True, help_text='SILIC 物種ID。', null=True)),
                ('scientificName', models.CharField(help_text='調查物種的拉丁學名，為鑑定至最低階層的完整學名。', max_length=255)),
                ('taxonRank', models.CharField(help_text='調查物種所列學名的鑑定層級。', max_length=64)),
                ('vernacularName', models.CharField(blank=True, help_text='物種學名以外的俗名，如中文俗名或英文俗名。', max_length=255, null=True)),
                ('soundclass', models.CharField(blank=True, help_text='叫聲類型，如：鳴唱或鳴叫聲分別以 S 或 C 表示。', max_length=16, null=True)),
                ('time_begin', models.FloatField(blank=True, help_text='鳥音在該錄音檔中的起始時間戳記（毫秒）。', null=True)),
                ('time_end', models.FloatField(blank=True, help_text='鳥音在該錄音檔中的結束時間戳記（毫秒）。', null=True)),
                ('confidence', models.FloatField(blank=True, help_text='模型對該筆辨識結果的置信程度，通常為 0–1 之間的數值。', null=True)),
                ('associatedMedia', models.CharField(blank=True, help_text='相關多媒體（以 URL 為主），在此為錄音檔案名稱。', max_length=1024, null=True)),
                ('freq_low', models.FloatField(blank=True, help_text='鳥音聲紋之最低頻率（Hz）。', null=True)),
                ('freq_high', models.FloatField(blank=True, help_text='鳥音聲紋之最高頻率（Hz）。', null=True)),
                ('measurementDeterminedDate', models.DateTimeField(help_text='測量項目的量測日期，在此為錄音紀錄起始的時間。')),
                ('locationID', models.CharField(help_text='地點代號，需參用共用樣站列表。', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BioSound',
                'verbose_name_plural': 'BioSound',
                'db_table': 'api_biosound',
            },
        ),
        migrations.CreateModel(
            name='BirdnetSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(help_text='每筆資料的辨識碼，以調查事件ID+流水號。', max_length=255)),
                ('eventID', models.CharField(help_text='每筆調查事件的辨識碼，以子計畫代碼+調查日期+地點+樣區編號為組成。', max_length=255)),
                ('vernacularName', models.CharField(blank=True, help_text='物種學名以外的俗名，如中文俗名或英文俗名。', max_length=255, null=True)),
                ('model', models.CharField(blank=True, help_text='鳥音辨識 BirdNET 模型版本。', max_length=255, null=True)),
                ('time_begin', models.FloatField(blank=True, help_text='鳥音在該錄音檔中的起始時間戳記（秒）。', null=True)),
                ('time_end', models.FloatField(blank=True, help_text='鳥音在該錄音檔中的結束時間戳記（秒）。', null=True)),
                ('confidence', models.FloatField(blank=True, help_text='模型對該筆辨識結果的置信程度，通常為 0–1 之間的數值。', null=True)),
                ('associatedMedia', models.CharField(blank=True, help_text='相關多媒體（以 URL 為主），在此為錄音檔案名稱。', max_length=1024, null=True)),
                ('measurementDeterminedDate', models.DateTimeField(blank=True, help_text='測量項目的量測日期，在此為錄音紀錄起始的時間。', null=True)),
                ('locationID', models.CharField(blank=True, help_text='地點代號，需參用共用樣站列表。', max_length=128, null=True)),
                ('deploymentID', models.CharField(help_text='機器部署的唯一識別碼', max_length=128)),
                ('taxonID', models.CharField(blank=True, help_text='由 TaiCOL 網站所定義的物種編號。', max_length=128, null=True)),
                ('scientificName', models.CharField(help_text='調查物種的拉丁學名，為鑑定至最低階層的完整學名。', max_length=255)),
                ('taxonRank', models.CharField(blank=True, help_text='調查物種所列學名的鑑定層級。', max_length=64, null=True)),
                ('scientificNameID', models.BigIntegerField(blank=True, help_text='由 TaiCOL 所賦予的學名的唯一識別碼。', null=True)),
                ('family', models.CharField(blank=True, help_text='生物分類單元「科」之科學名稱。', max_length=255, null=True)),
                ('familyChinese', models.CharField(blank=True, help_text='科中文名。', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BirdnetSound',
                'verbose_name_plural': 'BirdnetSound',
                'db_table': 'api_birdnetsound',
            },
        ),
        migrations.CreateModel(
            name='TerreSoundIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(help_text='每筆資料的辨識碼，以調查事件ID+流水號', max_length=255)),
                ('eventID', models.CharField(help_text='每筆調查事件的辨識碼，以子計畫代碼+調查日期+地點+樣區編號為組成', max_length=255)),
                ('sh', models.FloatField(blank=True, help_text='Spectral entropy，量化聲音能量在頻譜上的分散程度', null=True)),
                ('th', models.FloatField(blank=True, help_text='Temporal entropy，量化聲音能量在時間上的分散程度', null=True)),
                ('H', models.FloatField(blank=True, help_text='Acoustic entropy index，描述能量在時間與頻率兩個面向上的分散程度', null=True)),
                ('ACI', models.FloatField(blank=True, help_text='Acoustic complexity index，量化頻率和能量在微細時間的變化', null=True)),
                ('ADI', models.FloatField(blank=True, help_text='Acoustic diversity index，量化聲音內容的多樣性（類似香儂多樣性指數）', null=True)),
                ('AEI', models.FloatField(blank=True, help_text='Acoustic evenness index，聲音均勻度指數（基於吉尼係數）', null=True)),
                ('BI', models.FloatField(blank=True, help_text='Bioacoustic index，用以描述環境中生物聲音的多寡', null=True)),
                ('NDSI', models.FloatField(blank=True, help_text='Normalized Difference Soundscape Index，量化生物聲音與人造聲音相對貢獻量', null=True)),
                ('associatedMedia', models.CharField(blank=True, help_text='相關多媒體，以 URL 為主；在此為錄音檔案名稱', max_length=1024, null=True)),
                ('min', models.PositiveIntegerField(blank=True, help_text='錄音長度：分鐘數', null=True)),
                ('sec', models.PositiveIntegerField(blank=True, help_text='錄音長度：秒數', null=True)),
                ('measurementDeterminedDate', models.DateTimeField(help_text='測量項目的量測日期，在此為錄音紀錄起始的時間')),
                ('locationID', models.CharField(max_length=128)),
                ('deploymentID', models.CharField(help_text='機器部署的唯一識別碼', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TerreSoundIndex',
                'verbose_name_plural': 'TerreSoundIndex',
                'db_table': 'api_terresoundindex',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(help_text="每筆資料的辨識碼，由事件編號加上流水號（以 '-' 連接）。", max_length=255)),
                ('eventID', models.CharField(help_text="每筆事件的辨識碼，由子計畫代碼、調查日期、部署代碼組成（以 '-' 連接）。", max_length=255)),
                ('locationID', models.CharField(help_text='地點代號，需參照共用樣站列表以保持一致性。', max_length=128)),
                ('deploymentID', models.CharField(help_text='機器部署的唯一識別碼，用於追蹤不同部署設備。', max_length=255)),
                ('eventDate', models.DateField(help_text='觀測事件發生的日期（ISO 8601：YYYY-MM-DD）。')),
                ('eventTime', models.CharField(help_text='觀測事件發生的時間（ISO 8601，格式如 hh:mm:ssZ 或 hh:mm:ss±hh:mm）。', max_length=20)),
                ('PAR', models.FloatField(help_text='光合作用有效輻射 PPFD（400–700 nm），單位 µmol/m²/s，範圍 0–4000。', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000)])),
                ('WetnessLevel', models.FloatField(blank=True, help_text='葉片表面濕潤程度之原始感測數值，數值越高表示越濕。', null=True)),
                ('AirTemperature', models.FloatField(help_text='氣溫（°C），範圍 -40.0 ~ 80.0。', validators=[django.core.validators.MinValueValidator(-40.0), django.core.validators.MaxValueValidator(80.0)])),
                ('RelativeHumidity', models.FloatField(help_text='相對溼度（%），範圍 0.0 ~ 100.0。', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('AirPressure', models.FloatField(help_text='大氣壓力（hPa），範圍 10.0 ~ 1200.0。', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(1200.0)])),
                ('WaterContent', models.FloatField(blank=True, help_text='土壤體積含水量（0.00 = 全乾，1.00 = 完全飽和），範圍 0.00 ~ 0.70。', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.7)])),
                ('SoilTemperature', models.FloatField(blank=True, help_text='土壤溫度（°C），範圍 -40.0 ~ 60.0。', null=True, validators=[django.core.validators.MinValueValidator(-40.0), django.core.validators.MaxValueValidator(60.0)])),
                ('WindDirection', models.FloatField(blank=True, help_text='風向（度），0°=北、90°=東、180°=南、270°=西。', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(359.0)])),
                ('WindSpeed', models.FloatField(blank=True, help_text='風速（m/s），範圍 0.0 ~ 30.0。', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('GustSpeed', models.FloatField(blank=True, help_text='瞬間風速（m/s），範圍 0.0 ~ 30.0。', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('Precipitation', models.FloatField(blank=True, help_text='降水量（mm），範圍 0.0 ~ 9999.9。', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999.9)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather',
                'verbose_name_plural': 'Weather',
                'db_table': 'api_weather',
            },
        ),
        migrations.RemoveIndex(
            model_name='cameratrap',
            name='api_camtrap_deploym_22af27_idx',
        ),
        migrations.RemoveIndex(
            model_name='cameratrap',
            name='api_camtrap_taxonID_0c4a6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='plantphenology',
            name='api_plant_p_eventID_f12eb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='plantphenology',
            name='api_plant_p_dataID_b0a4b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='plantphenology',
            name='api_plant_p_taxonID_977bd4_idx',
        ),
        migrations.RemoveIndex(
            model_name='plantphenology',
            name='api_plant_p_scienti_35416b_idx',
        ),
        migrations.RemoveField(
            model_name='plantphenology',
            name='recordedBy',
        ),
        migrations.AlterField(
            model_name='cameratrap',
            name='deploymentID',
            field=models.CharField(help_text='機器部署的唯一識別碼', max_length=128),
        ),
        migrations.AlterField(
            model_name='cameratrap',
            name='observationID',
            field=models.CharField(help_text='觀察物種的識別碼', max_length=256),
        ),
        migrations.AlterField(
            model_name='cameratrap',
            name='scientificNameID',
            field=models.CharField(blank=True, help_text='TaiCOL 學名識別碼', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cameratrap',
            name='taxonID',
            field=models.CharField(blank=True, help_text='TaiCOL 物種編號', max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='cameratrap',
            index=models.Index(fields=['locationID'], name='api_camtrap_locatio_49c36c_idx'),
        ),
        migrations.AddIndex(
            model_name='plantphenology',
            index=models.Index(fields=['eventDate'], name='api_plant_p_eventDa_7d1f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='plantphenology',
            index=models.Index(fields=['locationID'], name='api_plant_p_locatio_397d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['eventDate'], name='api_weather_eventDa_1defa4_idx'),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['locationID'], name='api_weather_locatio_3d04c0_idx'),
        ),
        migrations.AddIndex(
            model_name='terresoundindex',
            index=models.Index(fields=['measurementDeterminedDate'], name='api_terreso_measure_15e3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='terresoundindex',
            index=models.Index(fields=['locationID'], name='api_terreso_locatio_0c421d_idx'),
        ),
        migrations.AddIndex(
            model_name='birdnetsound',
            index=models.Index(fields=['measurementDeterminedDate'], name='api_birdnet_measure_a428d2_idx'),
        ),
        migrations.AddIndex(
            model_name='birdnetsound',
            index=models.Index(fields=['locationID'], name='api_birdnet_locatio_7268e4_idx'),
        ),
        migrations.AddIndex(
            model_name='biosound',
            index=models.Index(fields=['measurementDeterminedDate'], name='api_biosoun_measure_8dea83_idx'),
        ),
        migrations.AddIndex(
            model_name='biosound',
            index=models.Index(fields=['locationID'], name='api_biosoun_locatio_4c0fa1_idx'),
        ),
    ]
