# Generated by Django 4.2.9 on 2025-11-17 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_biosound_birdnetsound_terresoundindex_weather_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cameratrap',
            new_name='api_camerat_eventDa_908db0_idx',
            old_name='api_camtrap_eventDa_30d7e8_idx',
        ),
        migrations.RenameIndex(
            model_name='cameratrap',
            new_name='api_camerat_locatio_887855_idx',
            old_name='api_camtrap_locatio_49c36c_idx',
        ),
        migrations.AlterModelTable(
            name='cameratrap',
            table='api_cameratrap',
        ),
    ]
