# Generated by Django 4.2.9 on 2025-11-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_api_camtrap_eventda_30d7e8_idx_api_camerat_eventda_908db0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosound',
            name='measurementDeterminedDate',
            field=models.DateField(help_text='測量項目的量測日期，在此為錄音紀錄起始的時間。'),
        ),
        migrations.AlterField(
            model_name='birdnetsound',
            name='measurementDeterminedDate',
            field=models.DateField(blank=True, help_text='測量項目的量測日期，在此為錄音紀錄起始的時間。', null=True),
        ),
        migrations.AlterField(
            model_name='terresoundindex',
            name='measurementDeterminedDate',
            field=models.DateField(help_text='測量項目的量測日期，在此為錄音紀錄起始的時間'),
        ),
    ]
