# Generated by Django 4.2.9 on 2025-11-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_biosound_measurementdetermineddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioSoundDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_name_zh_tw', models.CharField(max_length=255)),
                ('field_name_en', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=100)),
                ('show_at_filter', models.BooleanField(default=True)),
                ('show_at_table', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_plant_biosound_data_field',
            },
        ),
        migrations.CreateModel(
            name='BirdnetSoundDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_name_zh_tw', models.CharField(max_length=255)),
                ('field_name_en', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=100)),
                ('show_at_filter', models.BooleanField(default=True)),
                ('show_at_table', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_plant_birdnetsound_data_field',
            },
        ),
        migrations.CreateModel(
            name='CameratrapDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_name_zh_tw', models.CharField(max_length=255)),
                ('field_name_en', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=100)),
                ('show_at_filter', models.BooleanField(default=True)),
                ('show_at_table', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_plant_cameratrap_data_field',
            },
        ),
        migrations.CreateModel(
            name='TerreSoundIndexDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_name_zh_tw', models.CharField(max_length=255)),
                ('field_name_en', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=100)),
                ('show_at_filter', models.BooleanField(default=True)),
                ('show_at_table', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_plant_terresoundindex_data_field',
            },
        ),
        migrations.CreateModel(
            name='WeatherDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_name_zh_tw', models.CharField(max_length=255)),
                ('field_name_en', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=100)),
                ('show_at_filter', models.BooleanField(default=True)),
                ('show_at_table', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_plant_weather_data_field',
            },
        ),
    ]
