# Generated by Django 4.2.9 on 2025-11-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_biosounddatafield_birdnetsounddatafield_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='plantphenology',
            new_name='api_plantph_eventDa_5c873e_idx',
            old_name='api_plant_p_eventDa_7d1f6d_idx',
        ),
        migrations.RenameIndex(
            model_name='plantphenology',
            new_name='api_plantph_locatio_18cc80_idx',
            old_name='api_plant_p_locatio_397d3a_idx',
        ),
        migrations.AlterModelTable(
            name='biosounddatafield',
            table='api_biosound_data_field',
        ),
        migrations.AlterModelTable(
            name='birdnetsounddatafield',
            table='api_birdnetsound_data_field',
        ),
        migrations.AlterModelTable(
            name='cameratrapdatafield',
            table='api_cameratrap_data_field',
        ),
        migrations.AlterModelTable(
            name='plantphenology',
            table='api_plantphenology',
        ),
        migrations.AlterModelTable(
            name='plantphenologydatafield',
            table='api_plantphenology_data_field',
        ),
        migrations.AlterModelTable(
            name='terresoundindexdatafield',
            table='api_terresoundindex_data_field',
        ),
        migrations.AlterModelTable(
            name='weatherdatafield',
            table='api_weather_data_field',
        ),
    ]
