# Generated by Django 4.2.9 on 2025-11-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_api_plant_p_eventda_7d1f6d_idx_api_plantph_eventda_5c873e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='AirPressure',
            field=models.FloatField(blank=True, help_text='大氣壓力（hPa），範圍 10.0 ~ 1200.0。', null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='AirTemperature',
            field=models.FloatField(blank=True, help_text='氣溫（°C），範圍 -40.0 ~ 80.0。', null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='GustSpeed',
            field=models.FloatField(blank=True, help_text='瞬間風速（m/s），範圍 0.0 ~ 30.0。', null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='PAR',
            field=models.FloatField(blank=True, help_text='光合作用有效輻射 PPFD（400–700 nm），單位 µmol/m²/s，範圍 0–4000。', null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='Precipitation',
            field=models.FloatField(blank=True, help_text='降水量（mm），範圍 0.0 ~ 9999.9。', null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='RelativeHumidity',
            field=models.FloatField(blank=True, help_text='相對溼度（%），範圍 0.0 ~ 100.0。', null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='SoilTemperature',
            field=models.FloatField(blank=True, help_text='土壤溫度（°C），範圍 -40.0 ~ 60.0。', null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='WaterContent',
            field=models.FloatField(blank=True, help_text='土壤體積含水量（0.00 = 全乾，1.00 = 完全飽和），範圍 0.00 ~ 0.70。', null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='WindDirection',
            field=models.FloatField(blank=True, help_text='風向（度），0°=北、90°=東、180°=南、270°=西。', null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='WindSpeed',
            field=models.FloatField(blank=True, help_text='風速（m/s），範圍 0.0 ~ 30.0。', null=True),
        ),
    ]
