# Generated by Django 4.2.9 on 2025-12-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_weather_airpressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('location_id', models.CharField(max_length=100)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField()),
                ('items', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('done', '已完成'), ('failed', '失敗')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('zip_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'DownloadRequest',
                'verbose_name_plural': 'DownloadRequests',
                'db_table': 'api_download_request',
            },
        ),
    ]
