# Generated by Django 4.2.9 on 2025-12-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_downloadrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
