# Generated by Django 4.2.9 on 2025-12-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_downloadrequest_email_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('done', '已完成'), ('failed', '失敗'), ('expired', '已過期')], default='pending', max_length=20),
        ),
    ]
