# Generated by Django 4.2.9 on 2025-12-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_downloadrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='mode',
            field=models.CharField(choices=[('selected', '指定項目下載'), ('item_all', '單一項目全域下載'), ('catalog', '名錄下載')], default='selected', max_length=20),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='location_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
