# Generated by Django 4.2.9 on 2025-12-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_downloadrequest_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
