# Generated by Django 4.2.9 on 2026-08-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_downloadrequest_location_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosounddatafield',
            name='filter_widget',
            field=models.CharField(choices=[('text', 'Text input'), ('select', 'Select'), ('combobox', 'Combobox')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='birdnetsounddatafield',
            name='filter_widget',
            field=models.CharField(choices=[('text', 'Text input'), ('select', 'Select'), ('combobox', 'Combobox')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='cameratrapdatafield',
            name='filter_widget',
            field=models.CharField(choices=[('text', 'Text input'), ('select', 'Select'), ('combobox', 'Combobox')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='plantphenologydatafield',
            name='filter_widget',
            field=models.CharField(choices=[('text', 'Text input'), ('select', 'Select'), ('combobox', 'Combobox')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='terresoundindexdatafield',
            name='filter_widget',
            field=models.CharField(choices=[('text', 'Text input'), ('select', 'Select'), ('combobox', 'Combobox')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='weatherdatafield',
            name='filter_widget',
            field=models.CharField(choices=[('text', 'Text input'), ('select', 'Select'), ('combobox', 'Combobox')], default='text', max_length=20),
        ),
    ]
