# Generated by Django 4.2.9 on 2025-11-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ecology', '生態觀測'), ('environment', '環境觀測'), ('ecological-economics', '生態經濟'), ('ecological-culture', '經濟與文化面向')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('media', models.ImageField(blank=True, null=True, upload_to='introductionImage/')),
            ],
            options={
                'verbose_name': 'Introduction',
                'verbose_name_plural': 'Introductions',
                'db_table': 'dashboard_introduction',
            },
        ),
    ]
