# Generated by Django 4.2.9 on 2025-11-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='content_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='introduction',
            name='name_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
