# Generated by Django 4.2.9 on 2025-11-07 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_introduction_content_en_introduction_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('promotion', '推廣介紹'), ('event', '活動參與'), ('training', '培力'), ('meeting', '會談諮詢')], max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CouEvent',
                'verbose_name_plural': 'CouEvent',
                'db_table': 'dashboard_cou_event',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='introduction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='introduction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
