# Generated by Django 4.2.9 on 2025-11-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_coueevent_introduction_created_at_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoueEvent",
            new_name="CouEvent",
        ),
        migrations.AlterModelOptions(
            name="couevent",
            options={
                "ordering": ["-date"],
                "verbose_name": "CouEvent",
                "verbose_name_plural": "CouEvents",
            },
        ),
        migrations.CreateModel(
            name="CouEventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="couEventImage/")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dashboard.couevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "CouEventImage",
                "verbose_name_plural": "CouEventsImages",
                "db_table": "dashboard_cou_event_image",
            },
        ),
    ]
