# Generated by Django 4.2.9 on 2025-11-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_couevent_options_rename_coueevent_couevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('promotion', '活動推廣'), ('event', '部落活動紀錄'), ('environment', '環境觀測紀錄'), ('local', '在地議題與討論')], max_length=50)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'dashboard_news',
                'ordering': ['-date'],
            },
        ),
    ]
