# Generated by Django 4.2.9 on 2025-11-12 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'NewsType',
                'verbose_name_plural': 'NewsTypes',
                'db_table': 'dashboard_news_type',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='type',
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newsImage/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.news')),
            ],
            options={
                'verbose_name': 'NewsImage',
                'verbose_name_plural': 'NewsImages',
                'db_table': 'dashboard_news_image',
            },
        ),
        migrations.CreateModel(
            name='NewsCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newsCoverImage/')),
                ('news_cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_image', to='dashboard.news')),
            ],
            options={
                'verbose_name': 'NewsCoverImage',
                'verbose_name_plural': 'NewsCoverImages',
                'db_table': 'dashboard_news_cover_image',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='news_list', to='dashboard.newstype'),
        ),
    ]
