# Generated by Django 4.2.9 on 2025-11-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_newstype_remove_news_type_newsimage_newscoverimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'FaqType',
                'verbose_name_plural': 'FaqTypes',
                'db_table': 'dashboard_faq_type',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('types', models.ManyToManyField(blank=True, related_name='faq_list', to='dashboard.faqtype')),
            ],
            options={
                'verbose_name': 'Faq',
                'verbose_name_plural': 'Faqs',
                'db_table': 'dashboard_faq',
            },
        ),
    ]
