# Generated by Django 4.2.9 on 2025-11-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_faqtype_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CouEventType',
                'verbose_name_plural': 'CouEventTypes',
                'db_table': 'dashboard_cou_event_type',
            },
        ),
        migrations.RemoveField(
            model_name='couevent',
            name='type',
        ),
        migrations.AddField(
            model_name='couevent',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='cou_event_list', to='dashboard.coueventtype'),
        ),
    ]
