# Generated by Django 4.2.9 on 2025-11-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_coueventtype_remove_couevent_type_couevent_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'LiteratureType',
                'verbose_name_plural': 'LiteratureTypes',
                'db_table': 'dashboard_literature_type',
            },
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('published_year', models.IntegerField()),
                ('author', models.TextField()),
                ('affiliation', models.TextField()),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('types', models.ManyToManyField(blank=True, related_name='literature_list', to='dashboard.literaturetype')),
            ],
            options={
                'verbose_name': 'Literature',
                'verbose_name_plural': 'Literatures',
                'db_table': 'dashboard_literature',
            },
        ),
    ]
