# Generated by Django 4.2.9 on 2025-11-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_literaturetype_literature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="literature",
            name="published_year",
        ),
        migrations.AddField(
            model_name="literature",
            name="date",
            field=models.DateField(default="2025-01-01"),
            preserve_default=False,
        ),
    ]
