# Generated by Django 4.2.9 on 2025-12-23 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_formlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('image', models.ImageField(blank=True, null=True, upload_to='contactsImage/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='計劃主持人預設放在 0', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'dashboard_contact',
            },
        ),
        migrations.AlterModelOptions(
            name='formlink',
            options={'verbose_name': 'FormLink', 'verbose_name_plural': 'FormLinks'},
        ),
        migrations.AlterModelTable(
            name='formlink',
            table='dashboard_formlink',
        ),
    ]
