# Generated by Django 4.2.9 on 2025-12-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_contact_alter_formlink_options_alter_formlink_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='計劃主持人預設放在 0'),
        ),
    ]
